
### Get task
GET http://localhost:3000/tasks/2


### Create new child
POST http://localhost:3000/tasks?parentTaskId=2
Content-Type: application/json

{
  "attributes": {
    "title": "new task created by REST client"
  }
}

### Delete task
DELETE http://localhost:3000/tasks/6
